# MPCC solver Return type
@enum(
    MPCCSolverStatus::Int,
    B_STATIONARY = 0,
    NLP_STATIONARY = 1,
    INFEASIBLE_PROBLEM_DETECTED=2,
    DIVERGING_ITERATES=3,
    MAXIMUM_ITERATIONS_EXCEEDED = 4,
    MAXIMUM_WALLTIME_EXCEEDED = 5,
    UNKNOWN = -1,
)
