module MadMPEC
using NLPModels


export AbstractMPCCModel,
    CCType,
    MPCCModel,
    MPCCModelVarVar,
    MPCCModelVarCon,
    MPCCModelConCon,
    MPCCVerticalForm,
    MPCCModelMeta,
    getproprty,
    ScholtesRelaxation,
    obj,
    grad,
    grad!,
    objgrad,
    objgrad!,
    objcons,
    objcons!,
    cons,
    cons!,
    cons_nl,
    cons_nl!,
    consG,
    consG!,
    consH,
    consH!,
    viol,
    viol!,
    jth_con,
    jth_congrad,
    jth_congrad!,
    jth_sparse_congrad,
    jac_structure!,
    jac_structure,
    jac_coord!,
    jac_coord,
    jac,
    jprod,
    jprod!,
    jtprod,
    jtprod!,
    jac_op,
    jac_op!,
    jac_nl_structure!,
    jac_nl_structure,
    jac_nl_coord!,
    jac_nl_coord,
    jac_nl,
    jnlprod,
    jnlprod!,
    jnltprod,
    jnltprod!,
    jac_nl_op,
    jac_nl_op!,
    comp_left,
    comp_left!,
    comp_right,
    comp_right!,
    lcomp_left,
    lcomp_left!,
    lcomp_right,
    lcomp_right!,
    comp_res_left!,
    comp_res_right!,
    jac_comp_left_structure,
    jac_comp_left_structure!,
    jac_comp_right_structure,
    jac_comp_right_structure!,
    jac_comp_left_coord,
    jac_comp_left_coord!,
    jac_comp_right_coord,
    jac_comp_right_coord!

include("Types.jl")
include("MappedVector.jl")
include("MPCCModelMeta.jl")
include("MPCCModel.jl")
include("ScholtesRelaxation.jl")

end # module MadMPEC
